# Generated by Cascade helper
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Tỉnh/Thành phố')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('default_radius_km', models.DecimalField(decimal_places=1, default=5.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Khu vực (Tỉnh/Thành)',
                'verbose_name_plural': 'Khu vực (Tỉnh/Thành)',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà hàng')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(verbose_name='Giờ mở cửa')),
                ('closing_time', models.TimeField(verbose_name='Giờ đóng cửa')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='restaurants.province', verbose_name='Tỉnh/Thành')),
            ],
            options={
                'verbose_name': 'Nhà hàng',
                'verbose_name_plural': 'Nhà hàng',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên món ăn')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(upload_to='foods/', verbose_name='Hình ảnh')),
                ('ingredients', models.TextField(blank=True, verbose_name='Nguyên liệu')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Calories')),
                ('preparation_time', models.IntegerField(default=15, verbose_name='Thời gian chuẩn bị (phút)')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Món ăn',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.food')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
