# Generated by Django 4.2.7 on 2025-09-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_banner_description_banner_end_date_banner_link_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
    ]
