# Generated by Django 4.2.7 on 2025-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_food_image_alter_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
    ]
