# Generated by Django 4.2.7 on 2025-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_review_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-is_active', '-created_at'], 'verbose_name': 'Khuyến mãi', 'verbose_name_plural': 'Khuyến mãi'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_to_all',
            field=models.BooleanField(default=True, verbose_name='Áp dụng cho tất cả món'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá trị khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='restaurants.food', verbose_name='Món ăn áp dụng'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giảm giá tối đa'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Đơn hàng tối thiểu'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Phần trăm giảm giá'), ('FIXED_AMOUNT', 'Giảm giá cố định'), ('BUY_X_GET_Y', 'Mua X tặng Y'), ('FREE_SHIPPING', 'Miễn phí vận chuyển')], default='PERCENTAGE', max_length=20, verbose_name='Loại khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='times_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Đã sử dụng'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Giới hạn sử dụng'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang hoạt động'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
    ]
