# Generated by Django 4.2.7 on 2026-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_promotion_options_promotion_apply_to_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(default=100, verbose_name='Số lượng còn lại trong ngày'),
        ),
    ]
