# Generated by Django 4.2.7 on 2026-01-04 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_allow_null_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ tín dụng'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('vnpay', 'VNPay'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ tín dụng'), ('momo', 'MoMo'), ('zalopay', 'ZaloPay'), ('vnpay', 'VNPay'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
