# Generated by Django 4.2.7 on 2026-01-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_payment_method_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('vnpay', 'VNPay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('vnpay', 'VNPay')], max_length=20),
        ),
    ]
