# Generated by Django 4.2.7 on 2025-10-30 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0006_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food_item', 'Món ăn'), ('restaurant', 'Nhà hàng'), ('cuisine', 'Loại ẩm thực'), ('price_range', 'Khoảng giá'), ('quantity', 'Số lượng'), ('delivery_time', 'Thời gian giao hàng'), ('payment_method', 'Phương thức thanh toán'), ('promo_code', 'Mã giảm giá')], max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('synonyms', models.JSONField(blank=True, default=list, help_text='Các từ đồng nghĩa hoặc cách gọi khác (lưu dạng JSON array)')),
            ],
            options={
                'verbose_name_plural': 'Chat entities',
            },
        ),
        migrations.CreateModel(
            name='ChatIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('greeting', 'Chào hỏi'), ('order_food', 'Đặt món'), ('ask_recommendation', 'Hỏi gợi ý'), ('check_order_status', 'Kiểm tra đơn hàng'), ('cancel_order', 'Hủy đơn hàng'), ('check_wallet', 'Kiểm tra ví'), ('topup_wallet', 'Nạp tiền vào ví'), ('ask_menu', 'Hỏi thực đơn'), ('ask_restaurant_info', 'Hỏi thông tin nhà hàng'), ('ask_promotion', 'Hỏi khuyến mãi'), ('feedback', 'Phản hồi, đánh giá'), ('other', 'Khác')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('training_phrases', models.JSONField(default=list, help_text='Các mẫu câu ví dụ cho intent này (lưu dạng JSON array)')),
                ('response_templates', models.JSONField(default=list, help_text='Các mẫu phản hồi cho intent này (lưu dạng JSON array)')),
                ('requires_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('favorite_cuisines', models.JSONField(blank=True, default=list)),
                ('disliked_ingredients', models.JSONField(blank=True, default=list)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('preferred_meal_times', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(default='Cuộc trò chuyện mới', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Người dùng'), ('bot', 'Bot'), ('system', 'Hệ thống')], max_length=10)),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_features.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên model')),
                ('model_type', models.CharField(choices=[('recommendation', 'Gợi ý món ăn'), ('chatbot', 'Chatbot'), ('sentiment', 'Phân tích cảm xúc')], max_length=20)),
                ('version', models.CharField(max_length=20, verbose_name='Phiên bản')),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, verbose_name='Cấu hình')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FoodView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=1)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.food')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_features.userpreference')),
            ],
            options={
                'unique_together': {('user_preference', 'food')},
            },
        ),
        migrations.CreateModel(
            name='FoodRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Điểm gợi ý')),
                ('reason', models.TextField(verbose_name='Lý do gợi ý')),
                ('recommendation_type', models.CharField(choices=[('collaborative', 'Lọc cộng tác'), ('content_based', 'Dựa trên nội dung'), ('hybrid', 'Kết hợp'), ('trending', 'Xu hướng'), ('similar_users', 'Người dùng tương tự')], max_length=20, verbose_name='Loại gợi ý')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.food', verbose_name='Món ăn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Gợi ý món ăn',
                'verbose_name_plural': 'Gợi ý món ăn',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'food')},
            },
        ),
    ]
