# Generated by Django 4.2.7 on 2025-10-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(blank=True, verbose_name='Địa chỉ lấy hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='SĐT lấy hàng'),
        ),
    ]
