# Generated by Django 4.2.7 on 2025-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_pickup_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('assigned', 'Đã giao shipper'), ('picked_up', 'Đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('assigned', 'Đã giao shipper'), ('picked_up', 'Đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
    ]
