# Generated by Django 4.2.7 on 2026-01-02 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_order_status_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('finding_shipper', 'Đang tìm tài xế'), ('ready', 'Sẵn sàng giao'), ('delivering', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('finding_shipper', 'Đang tìm tài xế'), ('ready', 'Sẵn sàng giao'), ('delivering', 'Đang giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
        migrations.CreateModel(
            name='ShipperLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper_locations', to='orders.order')),
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
