# Generated by Django 4.2.7 on 2026-01-04 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_add_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('finding_shipper', 'Đang tìm tài xế'), ('ready', 'Sẵn sàng giao'), ('picked_up', 'Shipper đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('finding_shipper', 'Đang tìm tài xế'), ('ready', 'Sẵn sàng giao'), ('picked_up', 'Shipper đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
    ]
