# Generated by Django 4.2.7 on 2026-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_customer_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('assigned', 'Đã giao cho shipper'), ('picked_up', 'Shipper đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('assigned', 'Đã giao cho shipper'), ('picked_up', 'Shipper đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
    ]
