# Generated by Django 4.2.7 on 2026-01-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_unpaid_assigned_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('assigned', 'Đã giao cho shipper'), ('picked_up', 'Shipper đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành'), ('cancelled_by_user', 'Khách hủy'), ('cancelled_by_seller', 'Nhà hàng hủy'), ('cancelled_by_shipper', 'Shipper hủy'), ('failed_delivery', 'Giao thất bại')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('assigned', 'Đã giao cho shipper'), ('picked_up', 'Shipper đã lấy hàng'), ('delivering', 'Đang giao'), ('delivered', 'Đã giao'), ('completed', 'Hoàn thành'), ('cancelled_by_user', 'Khách hủy'), ('cancelled_by_seller', 'Nhà hàng hủy'), ('cancelled_by_shipper', 'Shipper hủy'), ('failed_delivery', 'Giao thất bại')], max_length=20),
        ),
    ]
