# Generated by Django 4.2.7 on 2026-01-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_update_order_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên khách (guest)'),
        ),
    ]
