# Generated by Django 4.2.7 on 2025-09-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_confirmed', 'Đơn hàng đã xác nhận'), ('order_preparing', 'Đang chuẩn bị'), ('order_ready', 'Sẵn sàng giao'), ('order_picked_up', 'Đã lấy hàng'), ('order_delivering', 'Đang giao'), ('order_delivered', 'Đã giao'), ('order_cancelled', 'Đơn hàng bị hủy'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('new_review', 'Đánh giá mới'), ('promotion', 'Khuyến mãi'), ('system', 'Thông báo hệ thống')], max_length=20, unique=True)),
                ('title_template', models.CharField(max_length=200, verbose_name='Mẫu tiêu đề')),
                ('message_template', models.TextField(verbose_name='Mẫu nội dung')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mẫu thông báo',
                'verbose_name_plural': 'Mẫu thông báo',
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
                'verbose_name_plural': 'Push Tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Đơn hàng mới'), ('order_confirmed', 'Đơn hàng đã xác nhận'), ('order_preparing', 'Đang chuẩn bị'), ('order_ready', 'Sẵn sàng giao'), ('order_picked_up', 'Đã lấy hàng'), ('order_delivering', 'Đang giao'), ('order_delivered', 'Đã giao'), ('order_cancelled', 'Đơn hàng bị hủy'), ('payment_success', 'Thanh toán thành công'), ('payment_failed', 'Thanh toán thất bại'), ('new_review', 'Đánh giá mới'), ('promotion', 'Khuyến mãi'), ('system', 'Thông báo hệ thống')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
